# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel
from pydantic import ConfigDict


class Balances(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvals: Dict[str, str]
    balance: str


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    map: Dict[str, str]


class Fa12TokenStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    administrator: str
    balances: Dict[str, Balances]
    debtCeiling: str
    governorContractAddress: str
    metadata: Dict[str, str]
    paused: bool
    token_metadata: Dict[str, TokenMetadata]
    totalSupply: str
