# generated by datamodel-codegen:
#   filename:  proposals_value.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel


class DiffItem(BaseModel):
    key: str
    new_value: Optional[str]


class ProposalType0(BaseModel):
    agora_post_id: str
    diff: List[DiffItem]


class Metadatum(BaseModel):
    proposal_type_0: ProposalType0


class ProposalType1(BaseModel):
    frozen_scale_value: Optional[str]
    frozen_extra_value: Optional[str]
    slash_scale_value: Optional[str]
    slash_division_value: Optional[str]
    max_proposal_size: Optional[str]


class Metadatum1(BaseModel):
    proposal_type_1: ProposalType1


class Metadatum2(BaseModel):
    receivers_0: List[str]


class Metadatum3(BaseModel):
    receivers_1: List[str]


class Voter(BaseModel):
    address: str
    nat: str


class ProposalsValue(BaseModel):
    upvotes: str
    downvotes: str
    start_date: str
    metadata: Union[Metadatum, Metadatum1, Metadatum2, Metadatum3]
    proposer: str
    proposer_frozen_token: str
    voters: List[Voter]
