# generated by datamodel-codegen:
#   filename:  registry_value.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class RegistryValue(BaseModel):
    value: Optional[str]
    affected_proposal_key: str
    last_updated: str
