# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import List

from pydantic import BaseModel
from pydantic import Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    address_0: str
    address_1: str
    nat: str


class Operator(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Dict[str, Any]


class TokenMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    token_id: str
    token_info: Dict[str, str]


class Assets(BaseModel):
    class Config:
        extra = Extra.forbid

    ledger: Dict[str, str]
    next_token_id: str
    operators: List[Operator]
    token_metadata: Dict[str, TokenMetadata]


class FtzFunStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    assets: Assets
    metadata: Dict[str, str]
