class InterfaceCodegenConst:
    CLASS_DEFINITION = 'class'
    METHOD_DEFINITION = 'async def'
    DEFAULT_PARAMETER_NAME = 'parameter'
    DEFAULT_RETURN_TYPE = 'None'
    COMMA_DELIMITER = ', '
    DOT_DELIMITER = '.'
    INTERFACE_FILENAME_POSTFIX = '_interface.py'
    INTERFACE_CLASS_POSTFIX = 'Interface'
    PARAMETER_TYPE_POSTFIX = 'Parameter'
    PARAMETER_SELF = 'self'
    EMPTY_STRING = ''
    MIXIN_MODULE = 'dipdup.interfaces.mixin'
    MIXIN_NAME = 'InterfaceMixin'
    ELLIPSIS = '...'
