# generated by DipDup 8.0.0b5

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class Royalties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    issuer: str
    royalties: str


class Swaps(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    issuer: str
    objkt_amount: str
    objkt_id: str
    xtz_per_objkt: str


class HenMinterStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    curate: str
    genesis: str
    hdao: str
    locked: bool
    manager: str
    metadata: dict[str, str]
    objkt: str
    objkt_id: str
    royalties: dict[str, Royalties]
    size: str
    swap_id: str
    swaps: dict[str, Swaps]
