# generated by datamodel-codegen:
#   filename:  Collect.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Collect(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    recipient: str
    tickLower: int
    tickUpper: int
    amount0: int
    amount1: int
