# generated by datamodel-codegen:
#   filename:  Flash.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Flash(BaseModel):
    class Config:
        extra = Extra.forbid

    sender: str
    recipient: str
    amount0: int
    amount1: int
    paid0: int
    paid1: int
