# generated by datamodel-codegen:
#   filename:  Initialize.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Initialize(BaseModel):
    class Config:
        extra = Extra.forbid

    sqrtPriceX96: int
    tick: int
