# generated by datamodel-codegen:
#   filename:  Mint.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Mint(BaseModel):
    class Config:
        extra = Extra.forbid

    sender: str
    owner: str
    tickLower: int
    tickUpper: int
    amount: int
    amount0: int
    amount1: int
