# generated by datamodel-codegen:
#   filename:  Swap.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class Swap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sender: str
    recipient: str
    amount0: int
    amount1: int
    sqrtPriceX96: int
    liquidity: int
    tick: int
