# generated by datamodel-codegen:
#   filename:  removeLiquidity.json

from __future__ import annotations

from pydantic import BaseModel


class RemoveLiquidityParameter(BaseModel):
    owner: str
    to: str
    lqtBurned: str
    minXtzWithdrawn: str
    minTokensWithdrawn: str
    deadline: str
