# generated by datamodel-codegen:
#   filename:  initial_auction.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class InitialAuction(BaseModel):
    auction_id_start: str
    token_ids: List[str]
