# generated by datamodel-codegen:
#   filename:  unit.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class UnitPayload(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
