# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import RootModel


class QwerStorageItem(BaseModel):
    model_config = ConfigDict(extra='forbid')

    L: str


class QwerStorageItem1(BaseModel):
    model_config = ConfigDict(extra='forbid')

    R: dict[str, str]


class QwerStorage(RootModel[Any]):
    root: list[list[QwerStorageItem | QwerStorageItem1]]
