# generated by DipDup 8.6.0

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class UnwrapPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    user: str
    token_address: str
    token_amount: str
    eth_token_address: str
    eth_address: str
