# generated by DipDup 8.5.2

from __future__ import annotations

from pydantic import BaseModel


class PoolCreatedPayload(BaseModel):
    token0: str
    token1: str
    fee: int
    tickSpacing: int
    pool: str
