# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class Ledger(BaseModel):
    approvals: Dict[str, str]
    balance: str


class TokenUSDtzStorage(BaseModel):
    admin: str
    ledger: Dict[str, Ledger]
    paused: bool
    totalSupply: str
