# generated by datamodel-codegen:
#   filename:  addLiquidity.json

from __future__ import annotations

from pydantic import BaseModel


class AddLiquidityParameter(BaseModel):
    owner: str
    minLqtMinted: str
    maxTokensDeposited: str
    deadline: str
