version: "3.8"

x-dipdup: &x-dipdup
  build: .
  depends_on:
    - db
  volumes:
    - ./src/demo_hic_et_nunc/dipdup.yml:/home/dipdup/dipdup.yml
  env_file: secrets.env

services:
  dipdup:
    <<: *x-dipdup
    restart: always
    command: ["-c", "dipdup.yml", "run"]

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    env_file: secrets.env

  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - 8080:8080
    depends_on:
    - db
    restart: always
    env_file: secrets.env

  configure-graphql:
    <<: *x-dipdup
    command: ["-c", "dipdup.yml", "configure-graphql", "--url", "http://graphql-engine:8080", "--admin-secret", "changeme"]
    depends_on:
      - graphql-engine
  
volumes:
  db: