FROM python:3.10-alpine AS compile-image
RUN apk add --update --no-cache build-base gcc musl-dev python3-dev libffi-dev openssl-dev cargo && \
    python -m venv --without-pip --system-site-packages /opt/dipdup && \
    mkdir -p /opt/dipdup/src/dipdup/ && \
    touch /opt/dipdup/src/dipdup/__init__.py
WORKDIR /opt/dipdup
ENV PATH="/opt/dipdup/bin:$PATH"
ENV PYTHON_PATH="/opt/dipdup/src:$PATH"

COPY pyproject.toml requirements.slim.txt README.md /opt/dipdup/

RUN /usr/local/bin/pip install --prefix /opt/dipdup --no-cache-dir --disable-pip-version-check -r /opt/dipdup/requirements.slim.txt && \
    /usr/local/bin/pip install --prefix /opt/dipdup --no-cache-dir --disable-pip-version-check --upgrade -e .

FROM python:3.10-alpine AS build-image

COPY --from=compile-image /opt/dipdup /opt/dipdup
COPY . /opt/dipdup

USER guest
ENV PATH="/opt/dipdup/bin:$PATH"
ENV PYTHONPATH="/opt/dipdup/src:/opt/dipdup/lib/python3.10/site-packages:$PYTHONPATH"
WORKDIR /home/dipdup/
ENTRYPOINT ["dipdup"]
CMD ["run"]
