version: "3.8"

x-dipdup: &x-dipdup
  build: .
  depends_on:
    - db
  volumes:
    - ./src/demo_hic_et_nunc/dipdup-docker.yml:/home/dipdup/dipdup.yml
  env_file: secrets.env

services:
  dipdup:
    <<: *x-dipdup
    restart: always
    command: ["-c", "dipdup.yml", "run"]
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgres/data
    env_file: secrets.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - 8080:8080
    depends_on:
    - db
    restart: always
    env_file: secrets.env
  
volumes:
  db: