# generated by datamodel-codegen:
#   filename:  collect.json

from __future__ import annotations

from pydantic import BaseModel


class CollectParameter(BaseModel):
    objkt_amount: str
    swap_id: str
