# generated by datamodel-codegen:
#   filename:  swap.json

from __future__ import annotations

from pydantic import BaseModel


class SwapParameter(BaseModel):
    objkt_amount: str
    objkt_id: str
    xtz_per_objkt: str
