# generated by datamodel-codegen:
#   filename:  propose.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra
from pydantic import Field


class ProposeParameter(BaseModel):
    class Config:
        extra = Extra.allow

    from_: str = Field(..., alias='from')
    frozen_token: str
    proposal_metadata: str
