# generated by datamodel-codegen:
#   filename:  tokenToTezPayment.json

from __future__ import annotations

from pydantic import BaseModel


class TokenToTezPayment(BaseModel):
    amount: str
    min_out: str
    receiver: str
