# generated by datamodel-codegen:
#   filename:  store_expiry_map_key.json

from __future__ import annotations

from pydantic import RootModel


class StoreExpiryMapKey(RootModel[str]):
    root: str
