# generated by datamodel-codegen:
#   filename:  store.expiry_map.value.json

from __future__ import annotations

from pydantic import BaseModel


class StoreExpiryMapValue(BaseModel):
    __root__: str
