# generated by datamodel-codegen:
#   filename:  store_expiry_map_value.json

from __future__ import annotations

from pydantic import BaseModel


class StoreExpiryMapValue(BaseModel):
    __root__: str
