# generated by DipDup 7.5.4

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class PoolCreated(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token0: str
    token1: str
    fee: int
    tickSpacing: int
    pool: str
