# generated by datamodel-codegen:
#   filename:  factory.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Factory(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
