# generated by datamodel-codegen:
#   filename:  multicall.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Multicall(BaseModel):
    class Config:
        extra = Extra.forbid

    data: str
