# generated by datamodel-codegen:
#   filename:  refundETH.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class RefundETH(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
