# generated by datamodel-codegen:
#   filename:  selfPermitIfNecessary.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class SelfPermitIfNecessary(BaseModel):
    class Config:
        extra = Extra.forbid

    token: str
    value: int
    deadline: int
    v: int
    r: str
    s: str
