# generated by datamodel-codegen:
#   filename:  selfPermitAllowed.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class SelfPermitAllowed(BaseModel):
    class Config:
        extra = Extra.forbid

    token: str
    nonce: int
    expiry: int
    v: int
    r: str
    s: str
