# generated by datamodel-codegen:
#   filename:  sweepToken.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class SweepToken(BaseModel):
    class Config:
        extra = Extra.forbid

    token: str
    amountMinimum: int
    recipient: str
