# generated by datamodel-codegen:
#   filename:  unwrapWETH9WithFee.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class UnwrapWETH9WithFee(BaseModel):
    class Config:
        extra = Extra.forbid

    amountMinimum: int
    recipient: str
    feeBips: int
    feeRecipient: str
