# generated by datamodel-codegen:
#   filename:  unwrapWETH9.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class UnwrapWETH9(BaseModel):
    class Config:
        extra = Extra.forbid

    amountMinimum: int
    recipient: str
