# generated by datamodel-codegen:
#   filename:  WETH9.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Weth9(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
