# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra
from pydantic import Field


class TzbtcStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    big_map: dict[str, str]
    lambda_: str = Field(..., alias='lambda')
    nat: str
    bool: bool
