# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


class TzbtcStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    big_map: Dict[str, str]
    lambda_: str = Field(..., alias='lambda')
    nat: str
    bool: bool
