# generated by DipDup 8.2.0

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class Token(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa12: str


class Fa2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    nat: str


class Token1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fa2: Fa2


class Content(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nat: str
    bytes: str | None = None


class TicketerStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: dict[str, str]
    token: Token | Token1
    content: Content
    total_supply: str
