# generated by datamodel-codegen:
#   filename:  setDelegate.json

from __future__ import annotations

from pydantic import BaseModel


class SetDelegateParameter(BaseModel):
    __root__: str | None
