# generated by datamodel-codegen:
#   filename:  setDelegate.json
from __future__ import annotations

from typing import Any

from pydantic import RootModel


class SetDelegateParameter(RootModel[Any]):
    root: str | None = None
