# generated by datamodel-codegen:
#   filename:  setDelegate.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class SetDelegateParameter(BaseModel):
    root: Optional[str] = None
