# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class KolibriOvensStorage(BaseModel):
    model_config = ConfigDict(extra='forbid')

    borrowedTokens: str
    interestIndex: str
    isLiquidated: bool
    ovenProxyContractAddress: str
    owner: str
    stabilityFeeTokens: str
