# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Records(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str | None
    data: dict[str, str]
    expiry_key: str | None
    internal_data: dict[str, str]
    level: str
    owner: str
    tzip12_token_id: str | None


class ReverseRecords(BaseModel):
    class Config:
        extra = Extra.forbid

    internal_data: dict[str, str]
    name: str | None
    owner: str


class Store(BaseModel):
    class Config:
        extra = Extra.forbid

    data: dict[str, str]
    expiry_map: dict[str, str]
    metadata: dict[str, str]
    next_tzip12_token_id: str
    owner: str
    records: dict[str, Records]
    reverse_records: dict[str, ReverseRecords]
    tzip12_tokens: dict[str, str]


class NameRegistryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    actions: dict[str, str]
    store: Store
    trusted_senders: list[str]
