# generated by datamodel-codegen:
#   filename:  divestLiquidity.json

from __future__ import annotations

from pydantic import BaseModel


class Divestliquidity(BaseModel):
    min_tez: str
    min_tokens: str
    shares: str
