# generated by datamodel-codegen:
#   filename:  getAllowance.json

from __future__ import annotations

from pydantic import BaseModel


class Getallowance(BaseModel):
    owner: str
    spender: str
    contract: str
