# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import RootModel


class Key(BaseModel):
    model_config = ConfigDict(extra='forbid')

    string: str
    nat: str


class AsdfStorageItem(BaseModel):
    model_config = ConfigDict(extra='forbid')

    key: Key
    value: str


class AsdfStorage(RootModel[Any]):
    root: list[dict[str, list[AsdfStorageItem]]]
