# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import List

from pydantic import BaseModel
from pydantic import ConfigDict


class Key(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    nat: str


class LedgerItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key
    value: str


class Key1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    owner: str
    operator: str
    token_id: str


class Operator(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: Key1
    value: Dict[str, Any]


class TokenMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_id: str
    token_info: Dict[str, str]


class HenObjktsStorage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    administrator: str
    all_tokens: str
    ledger: List[LedgerItem]
    metadata: Dict[str, str]
    operators: List[Operator]
    paused: bool
    token_metadata: Dict[str, TokenMetadata]
