# generated by datamodel-codegen:
#   filename:  set_child_record.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel


class SetChildRecord(BaseModel):
    address: Optional[str]
    data: Dict[str, str]
    expiry: Optional[str]
    label: str
    owner: str
    parent: str
