# generated by datamodel-codegen:
#   filename:  investLiquidity.json

from __future__ import annotations

from pydantic import RootModel


class InvestLiquidityParameter(RootModel[str]):
    root: str
