# generated by datamodel-codegen:
#   filename:  tokenToTezPayment.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class TokenToTezPaymentParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    min_out: str
    receiver: str
