# generated by datamodel-codegen:
#   filename:  withdrawProfit.json

from __future__ import annotations

from pydantic import RootModel


class WithdrawProfitParameter(RootModel[str]):
    root: str
