# generated by DipDup 8.0.0b5

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class StoreRecordsValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str | None = None
    data: dict[str, str]
    expiry_key: str | None = None
    internal_data: dict[str, str]
    level: str
    owner: str
    tzip12_token_id: str | None = None
