# generated by DipDup 8.3.1

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Field


class TransferPayload(BaseModel):
    from_: str = Field(..., alias='from')
    to: str
    value: int
