# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class Accounts(BaseModel):
    allowance: Dict[str, str]
    balance: str


class DexterFa12KUSDStorage(BaseModel):
    accounts: Dict[str, Accounts]
    freezeBaker: bool
    lqtTotal: str
    manager: str
    selfIsUpdatingTokenPool: bool
    tokenAddress: str
    tokenPool: str
    xtzPool: str
