# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict
from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    string: str


class Value(BaseModel):
    class Config:
        extra = Extra.forbid

    mr: Optional[Dict[str, bool]]
    sw: Optional[str]


class HjklStorageItem(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: Value


class HjklStorage(BaseModel):
    __root__: List[HjklStorageItem]
