# generated by datamodel-codegen:
#   filename:  propose.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class ProposeParameter(BaseModel):
    frozen_token: str
    proposal_metadata: Dict[str, str]
