# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel


class Ledger(BaseModel):
    allowances: List[str]
    balance: str


class TokenMetadata(BaseModel):
    token_id: str
    token_info: Dict[str, str]


class TokenFLAMEStorage(BaseModel):
    admin: str
    ledger: Dict[str, Ledger]
    metadata: Dict[str, str]
    minters: List[str]
    paused: bool
    token_metadata: Dict[str, TokenMetadata]
    total_supply: str
