# generated by datamodel-codegen:
#   filename:  move.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class MovePayload(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    a: str
    b: str
    roll: str
    epoch: str
    rolls: str
