# generated by datamodel-codegen:
#   filename:  AddedBlackList.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class AddedBlackList(BaseModel):
    class Config:
        extra = Extra.forbid

    user: str
