# generated by datamodel-codegen:
#   filename:  Deprecate.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Deprecate(BaseModel):
    class Config:
        extra = Extra.forbid

    newAddress: str
