# generated by datamodel-codegen:
#   filename:  DestroyedBlackFunds.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class DestroyedBlackFunds(BaseModel):
    class Config:
        extra = Extra.forbid

    blackListedUser: str
    balance: int
