# generated by datamodel-codegen:
#   filename:  Issue.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Issue(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: int
