# generated by datamodel-codegen:
#   filename:  Params.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Params(BaseModel):
    class Config:
        extra = Extra.forbid

    feeBasisPoints: int
    maxFee: int
