# generated by datamodel-codegen:
#   filename:  RemovedBlackList.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class RemovedBlackList(BaseModel):
    class Config:
        extra = Extra.forbid

    user: str
