# generated by datamodel-codegen:
#   filename:  Unpause.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Unpause(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
