# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict
from typing import List
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class QwerStorageItem(BaseModel):
    class Config:
        extra = Extra.forbid

    L: str


class QwerStorageItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    R: Dict[str, str]


class QwerStorage(BaseModel):
    __root__: List[List[Union[QwerStorageItem, QwerStorageItem1]]]
