# generated by datamodel-codegen:
#   filename:  royalties_value.json

from __future__ import annotations

from pydantic import BaseModel


class RoyaltiesValue(BaseModel):
    issuer: str
    royalties: str
