# generated by datamodel-codegen:
#   filename:  balance_of.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Request(BaseModel):
    owner: str
    token_id: str


class BalanceOf(BaseModel):
    requests: List[Request]
    callback: str
