# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Royalties(BaseModel):
    class Config:
        extra = Extra.forbid

    issuer: str
    royalties: str


class Swaps(BaseModel):
    class Config:
        extra = Extra.forbid

    issuer: str
    objkt_amount: str
    objkt_id: str
    xtz_per_objkt: str


class HenMinterStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    curate: str
    genesis: str
    hdao: str
    locked: bool
    manager: str
    metadata: dict[str, str]
    objkt: str
    objkt_id: str
    royalties: dict[str, Royalties]
    size: str
    swap_id: str
    swaps: dict[str, Swaps]
