database:
  kind: postgres
  host: ${POSTGRES_HOST:-demo_etherlink_db}
  port: 5432
  user: ${POSTGRES_USER:-dipdup}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB:-dipdup}

hasura:
  url: http://${HASURA_HOST:-demo_etherlink_hasura}:8080
  admin_secret: ${HASURA_SECRET}
  allow_aggregations: ${HASURA_ALLOW_AGGREGATIONS:-false}
  select_limit: ${HASURA_SELECT_LIMIT:-100}
  camel_case: ${HASURA_CAMEL_CASE:-true}

sentry:
  dsn: ${SENTRY_DSN:-''}
  environment: ${SENTRY_ENVIRONMENT:-''}

prometheus:
  host: 0.0.0.0