# Run `dipdup new --replay configs/replay.yaml` to generate new project from this replay
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_domains
  package: demo_domains
  version: 0.0.1
  description: Tezos Domains name service
  license: MIT
  name: John Doe
  email: john_doe@example.com
  postgresql_image: postgres:15
  hasura_image: hasura/graphql-engine:v2.30.0
  line_length: 120
