# generated by datamodel-codegen:
#   filename:  roll.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class RollPayload(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    bool: bool
