# generated by datamodel-codegen:
#   filename:  getAdministrator.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel


class Getadministrator(BaseModel):
    unit: Dict[str, Any]
    contract: str
