# generated by datamodel-codegen:
#   filename:  getTotalSupply.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel


class Gettotalsupply(BaseModel):
    unit: Dict[str, Any]
    contract: str
