# generated by datamodel-codegen:
#   filename:  setGovernorContract.json

from __future__ import annotations

from pydantic import BaseModel


class Setgovernorcontract(BaseModel):
    __root__: str
