# generated by datamodel-codegen:
#   filename:  updateTokenMetadata.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Map(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: str


class Updatetokenmetadata(BaseModel):
    nat: str
    map: Dict[str, Map]
