# generated by datamodel-codegen:
#   filename:  updateContractMetadata.json

from __future__ import annotations

from pydantic import BaseModel


class Updatecontractmetadata(BaseModel):
    string: str
    bytes: str
