# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Metadata(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: str


class Royalties(BaseModel):
    class Config:
        extra = Extra.allow

    issuer: str
    royalties: str


class Swaps(BaseModel):
    class Config:
        extra = Extra.allow

    issuer: str
    objkt_amount: str
    objkt_id: str
    xtz_per_objkt: str


class Storage(BaseModel):
    curate: str
    genesis: str
    hdao: str
    locked: bool
    manager: str
    metadata: Dict[str, Metadata]
    objkt: str
    objkt_id: str
    royalties: Dict[str, Royalties]
    size: str
    swap_id: str
    swaps: Dict[str, Swaps]
