# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, Union

from pydantic import BaseModel


class Royalties(BaseModel):
    issuer: str
    royalties: str


class Swaps(BaseModel):
    issuer: str
    objkt_amount: str
    objkt_id: str
    xtz_per_objkt: str


class HenMinterStorage(BaseModel):
    curate: str
    genesis: str
    hdao: str
    locked: bool
    manager: str
    metadata: Union[int, Dict[str, str]]
    objkt: str
    objkt_id: str
    royalties: Union[int, Dict[str, Royalties]]
    size: str
    swap_id: str
    swaps: Union[int, Dict[str, Swaps]]
