# generated by datamodel-codegen:
#   filename:  option.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class OptionPayload(BaseModel):
    __root__: Optional[str]
