# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class ResourceMap(BaseModel):
    class Config:
        extra = Extra.forbid

    id: str
    rate: str


class ResourceCollectorStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    administrator: str
    current_user: str | None
    default_start_time: str
    generation_rate: str
    managers: list[str]
    metadata: dict[str, str]
    nft_registry: str
    paused: bool
    resource_map: dict[str, ResourceMap]
    resource_registry: str
    tezotop_collection: dict[str, str]
