# generated by DipDup 8.0.0b5

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import RootModel


class TzcolorsAuctionStorage1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    token_address: str
    token_id: str
    token_amount: str
    end_timestamp: str
    seller: str
    bid_amount: str
    bidder: str


class TzcolorsAuctionStorage(RootModel[dict[str, TzcolorsAuctionStorage1] | None]):
    root: dict[str, TzcolorsAuctionStorage1] | None = None
