# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, List, Union

from pydantic import BaseModel, Extra


class Metadatum(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class TokenMetadatum(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class Storage(BaseModel):
    administrator: str
    all_tokens: str
    ledger: Union[int, List[Any]]
    metadata: Union[int, Metadatum]
    operators: Union[int, List[Any]]
    paused: bool
    token_metadata: Union[int, TokenMetadatum]
