# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List, Union

from pydantic import BaseModel


class Auctions(BaseModel):
    ends_at: str
    last_bid: str
    last_bidder: str
    ownership_period: str


class Records(BaseModel):
    expiry: str
    internal_data: Dict[str, str]


class Store(BaseModel):
    auctions: Union[int, Dict[str, Auctions]]
    bidder_balances: Union[int, Dict[str, str]]
    commitments: Union[int, Dict[str, str]]
    config: Dict[str, str]
    data: Union[int, Dict[str, str]]
    metadata: Union[int, Dict[str, str]]
    name_registry: str
    owner: str
    records: Union[int, Dict[str, Records]]
    tld: str


class Storage(BaseModel):
    actions: Union[int, Dict[str, str]]
    store: Store
    trusted_senders: List[str]
