# generated by datamodel-codegen:
#   filename:  tezToTokenPayment.json

from __future__ import annotations

from pydantic import BaseModel


class TezToTokenPaymentParameter(BaseModel):
    min_out: str
    receiver: str
