# generated by datamodel-codegen:
#   filename:  Collect.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class Collect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokenId: int
    recipient: str
    amount0: int
    amount1: int
