FROM dipdup/dipdup:{{ cookiecutter.dipdup_version }}
# FROM dipdup/dipdup:{{ cookiecutter.dipdup_version }}-pytezos
# FROM dipdup/dipdup:{{ cookiecutter.dipdup_version }}-slim

# Optional: install additional dependencies using poetry
# COPY pyproject.toml poetry.lock .
# RUN install_dependencies

# Optional: install additional dependencies using pip
# COPY requirements.txt .
# RUN install_dependencies requirements.txt

COPY . .