.PHONY: $(MAKECMDGOALS)
MAKEFLAGS += --no-print-directory
##
##  🚧 DipDup developer tools
##
PACKAGE={{ project.package }}
TAG=latest
COMPOSE=deploy/compose.yaml

help:           ## Show this help (default)
	@grep -Fh "##" $(MAKEFILE_LIST) | grep -Fv grep -F | sed -e 's/\\$$//' | sed -e 's/##//'

all:            ## Run an entire CI pipeline
	make format lint

##

install:        ## Install dependencies
{%- if project.package_manager == 'none' %}
	true
{%- elif project.package_manager == 'pdm' %}
	pdm install
{%- elif project.package_manager == 'poetry' %}
	poetry install
{% endif %}

update:         ## Update dependencies
{%- if project.package_manager == 'none' %}
	true
{%- elif project.package_manager == 'pdm' %}
	pdm update
	dipdup self update -q
{%- elif project.package_manager == 'poetry' %}
	poetry update
	dipdup self update -q
{% endif %}

format:         ## Format with all tools
	make black

lint:           ## Lint with all tools
	make ruff mypy

##

black:          ## Format with black
	black .

ruff:           ## Lint with ruff
	ruff check --fix .

mypy:           ## Lint with mypy
	mypy .

##

image:          ## Build Docker image
	docker buildx build . -t ${PACKAGE}:${TAG} --load

up:             ## Start Compose stack
	docker-compose -f ${COMPOSE} up -d --build
	docker-compose -f ${COMPOSE} logs -f

down:           ## Stop Compose stack
	docker-compose -f ${COMPOSE} down

##