# generated by datamodel-codegen:
#   filename:  _totalSupply.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class FieldTotalSupply(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
