# generated by datamodel-codegen:
#   filename:  addBlackList.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class AddBlackList(BaseModel):
    class Config:
        extra = Extra.forbid

    evilUser: str
