# generated by datamodel-codegen:
#   filename:  allowance.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Allowance(BaseModel):
    class Config:
        extra = Extra.forbid

    owner: str
    spender: str
