# generated by datamodel-codegen:
#   filename:  approve.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Approve(BaseModel):
    class Config:
        extra = Extra.forbid

    spender: str
    value: int
