# generated by datamodel-codegen:
#   filename:  balances.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Balances(BaseModel):
    class Config:
        extra = Extra.forbid

    field_: str
