# generated by datamodel-codegen:
#   filename:  balanceOf.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class BalanceOf(BaseModel):
    class Config:
        extra = Extra.forbid

    who: str
