# generated by datamodel-codegen:
#   filename:  basisPointsRate.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class BasisPointsRate(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
