# generated by datamodel-codegen:
#   filename:  decimals.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Decimals(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
