# generated by datamodel-codegen:
#   filename:  deprecated.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Deprecated(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
