# generated by datamodel-codegen:
#   filename:  destroyBlackFunds.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class DestroyBlackFunds(BaseModel):
    class Config:
        extra = Extra.forbid

    blackListedUser: str
