# generated by datamodel-codegen:
#   filename:  getBlackListStatus.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class GetBlackListStatus(BaseModel):
    class Config:
        extra = Extra.forbid

    maker: str
