# generated by datamodel-codegen:
#   filename:  getOwner.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class GetOwner(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
