# generated by datamodel-codegen:
#   filename:  isBlackListed.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class IsBlackListed(BaseModel):
    class Config:
        extra = Extra.forbid

    field_: str
