# generated by datamodel-codegen:
#   filename:  MAX_UINT.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class MAXUINT(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
