# generated by datamodel-codegen:
#   filename:  maximumFee.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class MaximumFee(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
