# generated by datamodel-codegen:
#   filename:  name.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Name(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
