# generated by datamodel-codegen:
#   filename:  owner.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Owner(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
