# generated by datamodel-codegen:
#   filename:  pause.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Pause(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
