# generated by datamodel-codegen:
#   filename:  removeBlackList.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class RemoveBlackList(BaseModel):
    class Config:
        extra = Extra.forbid

    clearedUser: str
