# generated by datamodel-codegen:
#   filename:  setParams.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class SetParams(BaseModel):
    class Config:
        extra = Extra.forbid

    newBasisPoints: int
    newMaxFee: int
