# generated by datamodel-codegen:
#   filename:  symbol.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Symbol(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
