# generated by datamodel-codegen:
#   filename:  totalSupply.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class TotalSupply(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
