# generated by datamodel-codegen:
#   filename:  transferOwnership.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class TransferOwnership(BaseModel):
    class Config:
        extra = Extra.forbid

    newOwner: str
