# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict
from typing import List
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class Key(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    string: str


class AsdfStorageItem(BaseModel):
    class Config:
        extra = Extra.forbid

    key: Key
    value: str


class AsdfStorage(BaseModel):
    __root__: List[Dict[str, Union[int, List[AsdfStorageItem]]]]
