# generated by datamodel-codegen:
#   filename:  xrate.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class XratePayload(BaseModel):
    class Config:
        extra = Extra.forbid

    evxtz: str
    xtz: str
