# generated by datamodel-codegen:
#   filename:  buy.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Extra


class Data(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: str


class Buy(BaseModel):
    label: str
    duration: str
    owner: str
    address: Optional[str]
    data: Dict[str, Data]
    nonce: str
