# generated by datamodel-codegen:
#   filename:  buy.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel


class Buy(BaseModel):
    label: str
    duration: str
    owner: str
    address: Optional[str]
    data: Dict[str, str]
    nonce: str
