# generated by DipDup 7.5.3

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class SwapParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    objkt_amount: str
    objkt_id: str
    xtz_per_objkt: str
