# generated by DipDup 8.0.0a1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class TransferPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: int = Field(..., alias='from')
    to: int
    value: int
