# generated by DipDup 8.3.0

from __future__ import annotations

from pydantic import BaseModel


class DecreaseLiquidityPayload(BaseModel):
    tokenId: int
    liquidity: int
    amount0: int
    amount1: int
