# generated by DipDup 8.2.2

from __future__ import annotations

from pydantic import BaseModel


class IncreaseLiquidityPayload(BaseModel):
    tokenId: int
    liquidity: int
    amount0: int
    amount1: int
