# generated by datamodel-codegen:
#   filename:  tezToTokenPayment.json

from __future__ import annotations

from pydantic import BaseModel


class TezToTokenPayment(BaseModel):
    min_out: str
    receiver: str
