# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import Union

from pydantic import BaseModel
from pydantic import Extra
from pydantic import Field


class BigMapItem(BaseModel):
    class Config:
        extra = Extra.forbid

    L: str


class BigMapItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    R: str


class MapItem(BaseModel):
    class Config:
        extra = Extra.forbid

    L: str


class MapItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    R: str


class OrItem(BaseModel):
    class Config:
        extra = Extra.forbid

    L: str


class OrItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    R: str


class ZxcvStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    big_map: Dict[str, Union[BigMapItem, BigMapItem1]]
    map: Dict[str, Union[MapItem, MapItem1]]
    or_: Union[OrItem, OrItem1] = Field(..., alias='or')
    unit: Dict[str, Any]
