spec_version: 1.2
package: demo_raw

database:
  kind: sqlite
  path: demo-raw.sqlite3

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: ${TZKT_URL:-https://api.tzkt.io}
    http:
      batch_size: 10000

indexes:
  mainnet_operations:
    kind: tezos.tzkt.operations_unfiltered
    datasource: tzkt_mainnet
    types:
      - origination
      - transaction
      - migration
    callback: on_operation
    first_level: 1589000
    last_level: 1590000