# generated by DipDup 7.5.3

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class MintParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to: str
    value: str
