# generated by datamodel-codegen:
#   filename:  execute.json

from __future__ import annotations

from pydantic import BaseModel


class ExecuteParameter(BaseModel):
    action_name: str
    original_sender: str
    payload: str
