# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel


class FreezeHistory(BaseModel):
    current_period_num: str
    current_unstaked: str
    past_unstaked: str
    staked: str


class LastPeriodChange(BaseModel):
    changed_on: str
    period_num: str


class Key(BaseModel):
    address: str
    nat: str


class LedgerItem(BaseModel):
    key: Key
    value: str


class MaxQuorumThreshold(BaseModel):
    denominator: str
    numerator: str


class MinQuorumThreshold(BaseModel):
    denominator: str
    numerator: str


class Key1(BaseModel):
    operator: str
    owner: str


class Operator(BaseModel):
    key: Key1
    value: Dict[str, Any]


class ProposalKeyListSortByDateItem(BaseModel):
    bytes: str
    timestamp: str


class Voter(BaseModel):
    vote_amount: str
    vote_type: bool
    voter_address: str


class Proposals(BaseModel):
    downvotes: str
    metadata: Dict[str, str]
    period_num: str
    proposer: str
    proposer_fixed_fee_in_token: str
    proposer_frozen_token: str
    start_date: str
    upvotes: str
    voters: List[Voter]


class QuorumThreshold(BaseModel):
    denominator: str
    numerator: str


class RegistryStorage(BaseModel):
    admin: str
    custom_entrypoints: Dict[str, str]
    decision_lambda: str
    extra: Dict[str, str]
    fixed_proposal_fee_in_token: str
    freeze_history: Dict[str, FreezeHistory]
    frozen_token_id: str
    last_period_change: LastPeriodChange
    ledger: List[LedgerItem]
    max_proposals: str
    max_quorum_threshold: MaxQuorumThreshold
    max_votes: str
    max_voting_period: str
    metadata: Dict[str, str]
    min_quorum_threshold: MinQuorumThreshold
    min_voting_period: str
    operators: List[Operator]
    pending_owner: str
    permits_counter: str
    proposal_check: str
    proposal_key_list_sort_by_date: List[ProposalKeyListSortByDateItem]
    proposals: Dict[str, Proposals]
    quorum_threshold: QuorumThreshold
    rejected_proposal_return_value: str
    token_address: str
    total_supply: Dict[str, str]
    unfrozen_token_id: str
    voting_period: str
