# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel


class Registry(BaseModel):
    affected_proposal_key: str
    last_updated: str
    value: Optional[str]


class Extra(BaseModel):
    frozen_extra_value: str
    frozen_scale_value: str
    max_proposal_size: str
    proposal_receivers: List[str]
    registry: Union[int, Dict[str, Registry]]
    slash_division_value: str
    slash_scale_value: str


class Key(BaseModel):
    address: str
    nat: str


class LedgerItem(BaseModel):
    key: Key
    value: str


class MigrationStatu(BaseModel):
    notInMigration: Dict[str, Any]


class MigrationStatu1(BaseModel):
    migratingTo: str


class MigrationStatu2(BaseModel):
    migratedTo: str


class Key1(BaseModel):
    operator: str
    owner: str


class Operator(BaseModel):
    key: Key1
    value: Dict[str, Any]


class ProposalKeyListSortByDateItem(BaseModel):
    bytes: str
    timestamp: str


class DiffItem(BaseModel):
    key: str
    new_value: Optional[str]


class ProposalType0(BaseModel):
    agora_post_id: str
    diff: List[DiffItem]


class Metadatum(BaseModel):
    proposal_type_0: ProposalType0


class ProposalType1(BaseModel):
    frozen_extra_value: Optional[str]
    frozen_scale_value: Optional[str]
    max_proposal_size: Optional[str]
    slash_division_value: Optional[str]
    slash_scale_value: Optional[str]


class Metadatum1(BaseModel):
    proposal_type_1: ProposalType1


class Metadatum2(BaseModel):
    receivers_0: List[str]


class Metadatum3(BaseModel):
    receivers_1: List[str]


class Voter(BaseModel):
    address: str
    nat: str


class Proposals(BaseModel):
    downvotes: str
    metadata: Union[Metadatum, Metadatum1, Metadatum2, Metadatum3]
    proposer: str
    proposer_frozen_token: str
    start_date: str
    upvotes: str
    voters: List[Voter]


class Storage(BaseModel):
    admin: str
    extra: Extra
    ledger: Union[int, List[LedgerItem]]
    metadata: Union[int, Dict[str, str]]
    migration_status: Union[MigrationStatu, MigrationStatu1, MigrationStatu2]
    operators: Union[int, List[Operator]]
    pending_owner: str
    permits_counter: str
    proposal_key_list_sort_by_date: List[ProposalKeyListSortByDateItem]
    proposals: Union[int, Dict[str, Proposals]]
    quorum_threshold: str
    token_address: str
    total_supply: Dict[str, str]
    voting_period: str
