# generated by datamodel-codegen:
#   filename:  default.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Data(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    bytes: str | None


class DefaultParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    data: Data
    amount: str
