# generated by datamodel-codegen:
#   filename:  deposit.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class DepositParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    rollup: str
    routing_info: str
    amount: str
