# generated by datamodel-codegen:
#   filename:  transfer.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import RootModel


class Tx(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    to_: str
    token_id: str
    amount: str


class TransferParameterItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    from_: str
    txs: List[Tx]


class TransferParameter(RootModel[List[TransferParameterItem]]):
    root: List[TransferParameterItem]
