# generated by datamodel-codegen:
#   filename:  xtzToToken.json

from __future__ import annotations

from pydantic import BaseModel


class XtzToTokenParameter(BaseModel):
    to: str
    minTokensBought: str
    deadline: str
