# generated by DipDup 8.0.0b5

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class MintParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    amount: str
    token_id: str
    token_info: dict[str, str]
