# generated by datamodel-codegen:
#   filename:  withdraw.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class Data(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    bytes: str | None


class Ticket(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    data: Data
    amount: str


class WithdrawParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    receiver: str
    ticket: Ticket
