# To refresh existing project run `dipdup init --base --force` after modifying this file.
# To generate a new project from this replay run `dipdup new --replay <path_to_file>`.
#
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_token_balances
  package: demo_token_balances
  version: 0.0.1
  description: TzBTC FA1.2 token balances
  license: MIT
  name: John Doe
  email: john_doe@example.com
  postgres_image: postgres:15
  postgres_data_path: /var/lib/postgresql/data
  hasura_image: hasura/graphql-engine:latest
  line_length: 120
  package_manager: pdm
