# generated by datamodel-codegen:
#   filename:  setDelegate.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class SetDelegateParameter(BaseModel):
    __root__: Optional[str]
