# generated by datamodel-codegen:
#   filename:  investLiquidity.json

from __future__ import annotations

from pydantic import BaseModel


class InvestLiquidityParameter(BaseModel):
    __root__: str
