[book]
authors = ["Baking Bad"]
language = "en"
multilingual = false
src = "."
title = "DipDup Documentation"

[build]
create-missing = false

[preprocessor.summary]
command = "python mdbook-summary"
