[book]
authors = ["Baking Bad"]
language = "en"
multilingual = false
src = "."
title = "DipDup framework"

# [output.linkcheck]
# follow-web-links = false

[preprocessor.summary]
command = "python mdbook-summary"