[book]
authors = ["Baking Bad"]
language = "en"
multilingual = false
src = "."
title = "DipDup Documentation"

[build]
create-missing = false

[output.html]
default-theme = "coal"
additional-css = ["book.css"]
git-repository-url = "https://github.com/dipdup-net/dipdup.git"

[preprocessor.summary]
command = "python mdbook-summary"

[preprocessor.cookiecutter]
command = "python mdbook-cookiecutter"
after = [ "links" ]