# generated by datamodel-codegen:
#   filename:  mint.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class MintParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    to: str
    value: str
