# generated by datamodel-codegen:
#   filename:  store_expiry_map_value.json

from __future__ import annotations

from pydantic import RootModel


class StoreExpiryMapValue(RootModel[str]):
    root: str
