# Run `dipdup new --replay configs/replay.yaml` to generate new project from this replay
spec_version: 2.0
replay:
  dipdup_version: 6
  template: demo_evm_events
  package: demo_evm_events
  version: 0.0.1
  description: Blockchain indexer built with DipDup
  license: MIT
  author: John Smith <john_smith@localhost.lan>
  postgresql_image: postgres:15
  hasura_image: hasura/graphql-engine:v2.28.0
  line_length: 120
