# generated by datamodel-codegen:
#   filename:  execute.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import ConfigDict


class ExecuteParameter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_name: str
    payload: str
    original_sender: str
