# generated by datamodel-codegen:
#   filename:  update_operators.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel


class AddOperator(BaseModel):
    owner: str
    operator: str
    token_id: str


class UpdateOperator(BaseModel):
    add_operator: AddOperator


class RemoveOperator(BaseModel):
    owner: str
    operator: str
    token_id: str


class UpdateOperator1(BaseModel):
    remove_operator: RemoveOperator


class UpdateOperators(BaseModel):
    __root__: List[Union[UpdateOperator, UpdateOperator1]]
