# Run `dipdup new --replay configs/replay.yaml` to generate new project from this replay
spec_version: 2.0
replay:
  dipdup_version: 6
  template: demo_dao
  package: demo_dao
  version: 0.0.1
  description: Blockchain indexer built with DipDup
  license: MIT
  name: John Smith
  email: john_smith@localhost.lan
  postgresql_image: postgres:15
  hasura_image: hasura/graphql-engine:v2.29.0 
  line_length: 120
