# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class Storage(BaseModel):
    pass

    class Config:
        extra = Extra.allow
