# generated by datamodel-codegen:
#   filename:  mint_OBJKT.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class MintOBJKTParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    amount: str
    metadata: str
    royalties: str
