# generated by datamodel-codegen:
#   filename:  tezos_storage.json

from __future__ import annotations

from typing import Dict
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class TzcolorsAuctionStorage1(BaseModel):
    class Config:
        extra = Extra.forbid

    token_address: str
    token_id: str
    token_amount: str
    end_timestamp: str
    seller: str
    bid_amount: str
    bidder: str


class TzcolorsAuctionStorage(BaseModel):
    __root__: Optional[Dict[str, TzcolorsAuctionStorage1]] = None
