# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict
from typing import List
from typing import Optional

from pydantic import ConfigDict, BaseModel


class Key(BaseModel):
    model_config = ConfigDict(extra="forbid")

    string: str
    nat: str


class Value(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sw: Optional[str]
    mr: Optional[Dict[str, bool]]


class HjklStorageItem(BaseModel):
    model_config = ConfigDict(extra="forbid")

    key: Key
    value: Value


class HjklStorage(BaseModel):
    root: List[HjklStorageItem]
