# generated by DipDup 8.6.1

from __future__ import annotations

from typing import TypedDict

V601 = TypedDict(
    'V601',
    {
        'asset_id': int,
        'from': str,
        'to': str,
        'amount': int,
    },
)
