# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel, Extra


class Key(BaseModel):
    token_id: str
    owner: str
    operator: str


class Allowance(BaseModel):
    key: Key
    value: bool


class Key1(BaseModel):
    token_id: str
    owner: str


class LedgerItem(BaseModel):
    key: Key1
    value: str


class TotalSupply(BaseModel):
    class Config:
        extra = Extra.allow

    __root__: str


class Storage(BaseModel):
    allowances: List[Allowance]
    initial_auction_house_address: str
    ledger: List[LedgerItem]
    token_metadata: str
    total_supply: Dict[str, TotalSupply]
