name: Test cookiecutter
on:
  push:
    paths:
      - 'cookiecutter/**'
      - '.github/workflows/cookiecutter.yml'

jobs:
  test:
    name: Test cookiecutter
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Create new project and ensure it's valid
        run: poetry run pip install cookiecutter && poetry run cookiecutter --no-input cookiecutter && cd my-dipdup-indexer && make all
