name: Docs (next)
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '**'
    paths:
      - 'docs/**'
      - 'scripts/**'
      - '.github/workflows/docs-next.yml'

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Set up mdbook
      uses: jontze/action-mdbook@v2
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        use-toc: true
        use-admonish: true

    - name: Install project
      run: make install

    - name: Build docs
      run: MDBOOK_ROOT=https://docs-next.dipdup.io make docs

    - name: Deploy to GitHub Pages
      if: equals(github.ref, 'refs/heads/master')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/dist/docs
        destination_dir: docs-next
