name: Installer
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/docs.yml'
      - '.github/workflows/installer.yml'

jobs:
  installer:
    name: Installer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # NOTE: Test full matrix there - it's less than a minute per run
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04
            arch: arm64
          - os: macos-15
            arch: amd64
          - os: macos-15
            arch: arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python 3.12
        run: uv python install 3.12

      # NOTE: GitHub updated cmake in macOS runners breaking `crypto-cpp-py` build
      # See https://github.com/actions/runner-images/issues/11926
      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.x'

      - name: Install DipDup
        run: uv run python src/dipdup/install.py --quiet --path .

      - name: dipdup new
        run: dipdup new --quiet
        
      - name: dipdup init
        run: cd dipdup_indexer; dipdup init

      - name: Install dev dependencies
        run: cd dipdup_indexer; make install; uv tool install --force ..

      - name: make all
        run: cd dipdup_indexer; source .venv/bin/activate; make all

      # NOTE: Installer is published in `docs` workflow
