name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@master
    - name: set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.x'
    - uses: snok/install-poetry@v1.1.1
    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install libsodium-dev libsecp256k1-dev libgmp-dev -y
        poetry install -v
    - name: Run tests
      run: poetry run pytest tests/
    - name: Poetry publish
      run: |
        poetry config http-basic.pypi __token__ ${{secrets.PYPI_TOKEN}}
        poetry build
        poetry publish
    - name: Build github release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
    - name: telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Pytezos ${{ env.RELEASE_VERSION }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ env.RELEASE_VERSION }}
    - name: slack notification
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: |
          Pytezos ${{ env.RELEASE_VERSION }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ env.RELEASE_VERSION }}
