name: Test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # NOTE: arm64 macos is the fastest runner. Full matrix is tested in `release.yml`.
        include:
          - os: macos-latest
            arch: arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run install
        run: make install

      - name: Run lint
        run: uv run make lint

      - name: Run tests
        run: uv run make test
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          ONFINALITY_API_KEY: ${{ secrets.ONFINALITY_API_KEY }}
