# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Union

from pydantic import BaseModel, Extra


class StorageItem(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class Storage(BaseModel):
    __root__: Union[int, StorageItem]
