# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class TzcolorsAuctionStorage(BaseModel):
    pass

    class Config:
        extra = Extra.allow
