# generated by datamodel-codegen:
#   filename:  burn.json

from __future__ import annotations

from pydantic import BaseModel


class Burn(BaseModel):
    from_: str
    token_id: str
    amount: str
