# generated by datamodel-codegen:
#   filename:  get_total_supply.json

from __future__ import annotations

from pydantic import BaseModel


class GetTotalSupply(BaseModel):
    viewParam: str
    viewCallbackTo: str
