# generated by datamodel-codegen:
#   filename:  getVotePermitCounter.json

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel


class Getvotepermitcounter(BaseModel):
    viewParam: Dict[str, Any]
    viewCallbackTo: str
