# generated by datamodel-codegen:
#   filename:  set_quorum_threshold.json

from __future__ import annotations

from pydantic import BaseModel


class SetQuorumThreshold(BaseModel):
    __root__: str
