# generated by datamodel-codegen:
#   filename:  transfer_contract_tokens.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Tx(BaseModel):
    to_: str
    token_id: str
    amount: str


class Param(BaseModel):
    from_: str
    txs: List[Tx]


class TransferContractTokens(BaseModel):
    contract_address: str
    params: List[Param]
