# generated by datamodel-codegen:
#   filename:  vote.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class PermitItem(BaseModel):
    key: str
    signature: str


class VoteItem(BaseModel):
    proposal_key: str
    vote_type: bool
    vote_amount: str
    permit: Optional[PermitItem]


class Vote(BaseModel):
    __root__: List[VoteItem]
