# generated by DipDup 8.2.2

from __future__ import annotations

from pydantic import BaseModel


class CollectPayload(BaseModel):
    owner: str
    recipient: str
    tickLower: int
    tickUpper: int
    amount0: int
    amount1: int
