# generated by DipDup 8.6.1

from __future__ import annotations

from pydantic import BaseModel


class FlashPayload(BaseModel):
    sender: str
    recipient: str
    amount0: int
    amount1: int
    paid0: int
    paid1: int
