# generated by DipDup 8.4.0

from __future__ import annotations

from pydantic import BaseModel


class MintPayload(BaseModel):
    sender: str
    owner: str
    tickLower: int
    tickUpper: int
    amount: int
    amount0: int
    amount1: int
