# generated by DipDup 8.3.4

from __future__ import annotations

from pydantic import BaseModel


class SwapPayload(BaseModel):
    sender: str
    recipient: str
    amount0: int
    amount1: int
    sqrtPriceX96: int
    liquidity: int
    tick: int
